version: '2'
services:
  minio:
    image: minio/minio
    container_name: minio
    volumes:
      - ./minio-data:/uploads
    environment:
      - MINIO_ACCESS_KEY=xxx
      - MINIO_SECRET_KEY=xxx
    ports:
      - 9000:9000
    command: server /uploads
